[MAIN] JC-1653 & JC-1719
The-New-Fork/openfood pull request #13
Opened 2022-09-06 08:48 UTC by kelvinsIAV

## Task
[JC-1653](https://thenewfork.atlassian.net/browse/JC-1653)
[JC-1719](https://thenewfork.atlassian.net/browse/JC-1719)

## Related Task (Optional)
JC-1653 <--> [JC-1546](https://thenewfork.atlassian.net/browse/JC-1546)
JC-1719 <--> [JC-1709](https://thenewfork.atlassian.net/browse/JC-1709)

## Summary
### JC-1653
The final message from block notify shows `converted 1 to 1e+08 coins.` before it exits. 
probably all sendToBatchXXXXX functions will fail in a very ugly way if null is passed in. we need better validation of argument passing.

### JC-1719
The change to the import-api was the first step, which was successful. However, the undesired consequence during testing was for larger numbers greater than the original 10-digit limit, requiring larger UTXO values.

We don’t want this. We want to use the alphanumeric code when the length of the integer is longer than 10, when it is 19 digits it is too big for an int value anyway as well, so alphanumeric code needs to be used.

## Changes
- Add result validation on `dateToSatoshi` function
- Add validations on `sendToBatchPON` & `sendToBatchTIN` functions

2022-09-06 16:23 UTC, imylomylo requested changes
```
instance-100-blocknotify-python-1       | pon is 123456789012345
instance-100-blocknotify-python-1       | converted 123456789012345 to 1234567.89012345 coins
```
the conditions don't seem to be working :(

2022-09-07 05:39 UTC, ekoiav submitted a review, later dismissed

2022-09-07 06:30 UTC, ekoiav approved these changes

2022-09-07 06:53 UTC, imylomylo approved these changes

2022-09-07 06:53 UTC, merged